import Head from "next/head";
import styles from "../styles/Home.module.css";
import MainLayout from "../components/layout/MainLayout";
import { Form, Input, Button } from "antd";
import { useCallback } from "react";

const URL_REGEX =
  /[-a-zA-Z0-9@:%_\+.~#?&//=]{2,256}\.[a-z]{2,4}\b(\/[-a-zA-Z0-9@:%_\+.~#?&//=]*)?/i;

export default function Home() {
  const onSubmit = useCallback((data) => {
    console.log(data);
  }, []);

  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>Shorten Your URL Here!</h2>

        <Form name="urlShortener" onFinish={onSubmit}>
          <Form.Item
            name="url"
            rules={[
              { required: true, message: "Cannot empty!" },
              { pattern: URL_REGEX, message: "Must be a url!" },
            ]}
          >
            <Input />
          </Form.Item>

          <Form.Item name="url">
            <Button type="primary" htmlType="submit">
              Submit
            </Button>
          </Form.Item>
        </Form>
      </main>

      <footer className={styles.footer}>
        Copyright 2021 &nbsp;
        <a
          href="https://ranggarifqi.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          ranggarifqi.com
        </a>
      </footer>
    </MainLayout>
  );
}
